// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/trivery-id/skadi/internal/product/services (interfaces: IProductLocationRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "gitlab.com/trivery-id/skadi/internal/product/domain"
	repositories "gitlab.com/trivery-id/skadi/internal/product/repositories"
)

// MockIProductLocationRepository is a mock of IProductLocationRepository interface.
type MockIProductLocationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIProductLocationRepositoryMockRecorder
}

// MockIProductLocationRepositoryMockRecorder is the mock recorder for MockIProductLocationRepository.
type MockIProductLocationRepositoryMockRecorder struct {
	mock *MockIProductLocationRepository
}

// NewMockIProductLocationRepository creates a new mock instance.
func NewMockIProductLocationRepository(ctrl *gomock.Controller) *MockIProductLocationRepository {
	mock := &MockIProductLocationRepository{ctrl: ctrl}
	mock.recorder = &MockIProductLocationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIProductLocationRepository) EXPECT() *MockIProductLocationRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockIProductLocationRepository) Add(arg0 context.Context, arg1 *domain.ProductLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockIProductLocationRepositoryMockRecorder) Add(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockIProductLocationRepository)(nil).Add), arg0, arg1)
}

// Delete mocks base method.
func (m *MockIProductLocationRepository) Delete(arg0 context.Context, arg1 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIProductLocationRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIProductLocationRepository)(nil).Delete), arg0, arg1)
}

// Find mocks base method.
func (m *MockIProductLocationRepository) Find(arg0 context.Context, arg1 uint64) (*domain.ProductLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*domain.ProductLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockIProductLocationRepositoryMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockIProductLocationRepository)(nil).Find), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockIProductLocationRepository) FindAll(arg0 context.Context, arg1 repositories.FindAllInput) ([]domain.ProductLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0, arg1)
	ret0, _ := ret[0].([]domain.ProductLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIProductLocationRepositoryMockRecorder) FindAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIProductLocationRepository)(nil).FindAll), arg0, arg1)
}

// Update mocks base method.
func (m *MockIProductLocationRepository) Update(arg0 context.Context, arg1 *domain.ProductLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIProductLocationRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIProductLocationRepository)(nil).Update), arg0, arg1)
}
