apiVersion: v1
kind: Service
metadata:
  name: eks-skadi
  namespace: eks-skadi
  labels:
    app: eks-skadi
spec:
  selector:
    app: eks-skadi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: eks-skadi
  name: ingress-skadi
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eks-skadi
                port: 
                  number: 80