apiVersion: v1
kind: Service
metadata:
  name: eks-skadi
  namespace: eks-skadi
  labels:
    app: eks-skadi
spec:
  selector:
    app: eks-skadi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000