image: golang:1.14

cache:
    paths:
        - /apt-cache
        - /go/src/github.com
        - /go/src/golang.org
        - /go/src/google.golang.org
        - /go/src/gopkg.in
        - vendor/

stages:
    - build
    - deploy


build-dev:
    stage: build
    variables:
        ENV: 'dev'
        EB_APP_NAME: 'skadi'
        ARTIFACT_NAME: '$EB_APP_NAME-$ENV-$CI_COMMIT_SHORT_SHA.zip'
    before_script:
        - apt-get update && apt-get install zip -y
    script:
        - GOOS=linux GOARCH=amd64 go build -mod=readonly -o bin/application
        - 'zip -r "$ARTIFACT_NAME" .'
    artifacts:
        paths:
            - $ARTIFACT_NAME
        expire_in: 30 min
    only:
        - master

deploy-dev:
    stage: deploy
    environment:
        name: develop
    image: 
        name: "amazon/aws-cli"
        entrypoint: [""]
    variables:
        ENV: 'dev'
        GIN_MODE: 'release'
        SILENT_GORM: 'true'
        EB_APP_NAME: 'skadi'
        EB_ENV_NAME: 'skadi-dev'
        S3_BUCKET: 'trivery-dev-skadi'
        VERSION: '$CI_COMMIT_SHORT_SHA'
        ARTIFACT_NAME: '$EB_APP_NAME-$ENV-$CI_COMMIT_SHORT_SHA.zip'
        REGION: 'ap-southeast-1'
    script:
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws configure set region $REGION
        - aws configure list-profiles
        - aws configure list
        - aws s3 ls
        - aws s3 cp ./$ARTIFACT_NAME s3://$S3_BUCKET/
        - >
          aws elasticbeanstalk create-application-version 
          --application-name $EB_APP_NAME 
          --version-label $VERSION 
          --source-bundle S3Bucket=$S3_BUCKET,S3Key=$ARTIFACT_NAME 
          --auto-create-application 
          --region=$REGION 
        - >
          aws elasticbeanstalk update-environment 
          --application-name $EB_APP_NAME 
          --environment-name $EB_ENV_NAME 
          --version-label $VERSION 
          --region=$REGION 
          --option-settings 
          Namespace=aws:elasticbeanstalk:application:environment,OptionName=ENV,Value=$ENV 
          Namespace=aws:elasticbeanstalk:application:environment,OptionName=GIN_MODE,Value=$GIN_MODE 
          Namespace=aws:elasticbeanstalk:application:environment,OptionName=SILENT_GORM,Value=$SILENT_GORM 
          Namespace=aws:elasticbeanstalk:application:environment,OptionName=VERSION,Value=$VERSION 
          Namespace=aws:elasticbeanstalk:application:environment,OptionName=AWS_SECRET_ACCESS_KEY,Value=$AWS_SECRET_ACCESS_KEY
          Namespace=aws:elasticbeanstalk:application:environment,OptionName=AWS_ACCESS_KEY_ID,Value=$AWS_ACCESS_KEY_ID
    only:
        - master
