FROM golang:1.17-alpine

WORKDIR /app

COPY . ./

# define args & env variables
ARG ENV
ARG VERSION
ARG GIN_MODE
ARG SILENT_GORM
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

ENV ENV=$ENV
ENV VERSION=$VERSION
ENV GIN_MODE=$GIN_MODE
ENV SILENT_GORM=$SILENT_GORM
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

RUN echo "building version $VERSION" &&\
    go build -o skadi

EXPOSE 5000

CMD ["./skadi"]