
type Order {
    id: ID!

    requesterID: ID!
    requester: User!
    shopperID: ID
    shopper: User
    productID: ID!
    product: Product!

    quantity: Int!
    unit: String!
    notes: String

    price: ProductPrice!

    deal: OrderDeal!
    state: OrderState!
    cancellations: [OrderCancellation!]

    details: [OrderDetails!]
}

type OrderDeal {
    location: String!
    method: String!
    time: Time!
    includeBox: Boolean!
}

type OrderState {
    lastState: String!

    TimeOrderCreated: Time
    TimeOrderAccepted: Time
    TimeOrderPurchased: Time
    TimeOrderOnTheWay: Time
    TimeOrderDelivered: Time
    TimeOrderReviewed: Time
    TimeOrderCompleted: Time
}

type OrderCancellation {
    createdAt: Time!
    reason: String!
}

type OrderDetails {
    key: String!
    value: Any!
}