
type Order {
    id: ID!
    requester: User!
    shopeer: User
    product: Product!

    quantity: Int!
    unit: String!
    notes: String

    price: ProductPrice!

    deal: OrderDeal!
    state: OrderState!
    cancellation: [OrderCancellation!]
}

type OrderDeal {
    location: String!
    method: String!
    time: Time!
    includeBox: Boolean!
}

type OrderState {
    lastState: String!

    TimeOrderCreated: Time
    TimeOrderAccepted: Time
    TimeOrderPurchased: Time
    TimeOrderOnTheWay: Time
    TimeOrderDelivered: Time
    TimeOrderReviewed: Time
    TimeOrderCompleted: Time
}

type OrderCancellation {
    createdAt: Time!
    reason: String!
}