
type Product {
    id: ID!
    createdAt: Time!

    name: String!
    description: String!
    imagesURLs: [String!]
    weight: String!
    dimensions: String!
    categories: [String!]

    locations: [ProductLocation!]  
    prices: [ProductPrice!]
}

type ProductLocation {
    id: ID!
    createdAt: Time!

    userID: ID!
    productID: ID!
    
    text: String!
    country: String!
    province: String!
    city: String!
    area: String!
    street: String!
    building: String!
    store: String!

    longitude: Float!
    latitude: Float!
}

type ProductPrice {
    id: ID!
    createdAt: Time!

    userID: ID!
    productID: ID!
    
    currency: String!
    price: Uint64!
    isPriceEstimated: Boolean!
}
