

type User {
    id: ID!
    createdAt: Time!

    name: String!
    email: String!
    phoneNumber: String!
    profilePictureURL: String!
    currencyMain: String!
    currencySub: String

    addresses: [Address!]
}

input RegisterUser {
    name: String!
    email: String!
    password: String!
}

input UpdateUser {
    id: ID!
    name: String
    phoneNumber: String
    profilePictureURL: String

    currencyMain: String
    currencySub: String
}

input UpdateUserPassword {
    id: ID!
    password: String!
    newPassword: String!
}