# GraphQL schema example
#
# https://gqlgen.com/getting-started/

# import TodoMutation from "../../internal/todo/services"

type Mutation {
    login(input: LoginInput!): AuthTokens!
    refreshToken(input: RefreshTokenInput!): AuthTokens!

    registerUser(input: RegisterUser!): User!
    updateUser(input: UpdateUser!): User!
    updateUserPassword(input: UpdateUserPassword!): Boolean!

    createProduct(input: CreateProduct!): Product!

    createProductLocation(input: CreateProductLocation!): ProductLocation!
    updateProductLocation(input: UpdateProductLocation!): ProductLocation!
    deleteProductLocation(input: DeleteProductLocation!): Boolean!

    createProductPrice(input: CreateProductPrice!): ProductPrice!
    updateProductPrice(input: UpdateProductPrice!): ProductPrice!
    deleteProductPrice(input: DeleteProductPrice!): Boolean!

    createOrder(input: CreateOrder!): Order!
    takeOrder(input: TakeOrder!): Boolean!
    dropOrder(input: DropOrder!): Boolean!
    deleteOrder(input: DeleteOrder!): Boolean!

    createTodo(input: CreateTodo!): Todo!
}
