# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Query {
	user(id: ID!): User!

	product(id: ID!): Product!
	products(limit: Int, offset: Int): [Product!]

	getTodos(userID: ID): [Todo!]!
}
