# GraphQL schema example
#
# https://gqlgen.com/getting-started/

type Query {
	user(id: ID!): User!

	product(id: ID!): Product!
	products(limit: Int, offset: Int): [Product!]

	order(id: ID!): Order!
	orders(userID: ID!, limit: Int, offset: Int): [Order!]
}
