version: 2
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:latest-alpine
    steps:
      - checkout
      - run:
          name: Run golangci-lint
          command: | 
            golangci-lint run --config ./golangci.yml --timeout=15m
      - run:
          name: Install & run hadolint (docker linter)
          command: |
            # Install hadolint
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x ./hadolint

            # Run linter
            ./hadolint Dockerfile

  test:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: Run unit tests
          environment:
            ENV: test
            TEST_RUNNER: "CircleCI"
          command: |
            go test -v ./...

  build: 
    machine: true
    environment:
      ENV: dev
      GIN_MODE: debug
      SILENT_GORM: "false"
    steps:
      - checkout
      - run: 
          name: "docker login"
          command: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: 
          name: "docker build and push"
          command: |
            export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
            docker build -t trivery/skadi:$SHORT_GIT_HASH -t trivery/skadi:latest \
              --build-arg ENV=$ENV \
              --build-arg VERSION=$SHORT_GIT_HASH \
              --build-arg GIN_MODE=$GIN_MODE \
              --build-arg SILENT_GORM=$SILENT_GORM \
              --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
              --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY .
            docker push trivery/skadi

workflows:
  version: 2
  build-workflow:
    jobs:
      - lint
      - test
      - build:
          requires:
            - lint
            - test