// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Address struct {
	ID          uint64     `json:"id"`
	CreatedAt   time.Time  `json:"createdAt"`
	DeletedAt   *time.Time `json:"deletedAt"`
	UserID      uint64     `json:"userID"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Country     string     `json:"country"`
	Province    string     `json:"province"`
	City        string     `json:"city"`
	Area        *string    `json:"area"`
	Street      *string    `json:"street"`
	Building    *string    `json:"building"`
	Longitude   *float64   `json:"longitude"`
	Latitude    *float64   `json:"latitude"`
}

type AuthTokens struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

type CreateOrder struct {
	Product   *CreateProduct   `json:"product"`
	ProductID *uint64          `json:"productID"`
	PriceID   *uint64          `json:"priceID"`
	Quantity  int              `json:"quantity"`
	Unit      string           `json:"unit"`
	Notes     string           `json:"notes"`
	Deal      *CreateOrderDeal `json:"deal"`
}

type CreateOrderDeal struct {
	Location   string    `json:"location"`
	Method     string    `json:"method"`
	Time       time.Time `json:"time"`
	IncludeBox bool      `json:"includeBox"`
}

type CreateProduct struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	ImagesURLs  []string               `json:"imagesURLs"`
	Weight      *string                `json:"weight"`
	Dimensions  *string                `json:"dimensions"`
	Categories  []string               `json:"categories"`
	Location    *CreateProductLocation `json:"location"`
	Price       *CreateProductPrice    `json:"price"`
}

type CreateProductLocation struct {
	ProductID *uint64  `json:"productID"`
	Text      string   `json:"text"`
	Country   string   `json:"country"`
	Province  string   `json:"province"`
	City      string   `json:"city"`
	Area      *string  `json:"area"`
	Street    *string  `json:"street"`
	Building  *string  `json:"building"`
	Store     *string  `json:"store"`
	Longitude *float64 `json:"longitude"`
	Latitude  *float64 `json:"latitude"`
}

type CreateProductPrice struct {
	ProductID        *uint64 `json:"productID"`
	Currency         string  `json:"currency"`
	Price            uint64  `json:"price"`
	IsPriceEstimated bool    `json:"isPriceEstimated"`
}

type DeleteOrder struct {
	ID uint64 `json:"id"`
}

type DeleteProductLocation struct {
	ID uint64 `json:"id"`
}

type DeleteProductPrice struct {
	ID uint64 `json:"id"`
}

type DropOrder struct {
	ID     uint64 `json:"id"`
	Reason string `json:"reason"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Order struct {
	ID            uint64              `json:"id"`
	RequesterID   uint64              `json:"requesterID"`
	Requester     *User               `json:"requester"`
	ShopperID     *uint64             `json:"shopperID"`
	Shopper       *User               `json:"shopper"`
	ProductID     uint64              `json:"productID"`
	Product       *Product            `json:"product"`
	Quantity      int                 `json:"quantity"`
	Unit          string              `json:"unit"`
	Notes         *string             `json:"notes"`
	Price         *ProductPrice       `json:"price"`
	Deal          *OrderDeal          `json:"deal"`
	State         *OrderState         `json:"state"`
	Cancellations []OrderCancellation `json:"cancellations"`
}

type OrderCancellation struct {
	CreatedAt time.Time `json:"createdAt"`
	Reason    string    `json:"reason"`
}

type OrderDeal struct {
	Location   string    `json:"location"`
	Method     string    `json:"method"`
	Time       time.Time `json:"time"`
	IncludeBox bool      `json:"includeBox"`
}

type OrderState struct {
	LastState          string     `json:"lastState"`
	TimeOrderCreated   *time.Time `json:"TimeOrderCreated"`
	TimeOrderAccepted  *time.Time `json:"TimeOrderAccepted"`
	TimeOrderPurchased *time.Time `json:"TimeOrderPurchased"`
	TimeOrderOnTheWay  *time.Time `json:"TimeOrderOnTheWay"`
	TimeOrderDelivered *time.Time `json:"TimeOrderDelivered"`
	TimeOrderReviewed  *time.Time `json:"TimeOrderReviewed"`
	TimeOrderCompleted *time.Time `json:"TimeOrderCompleted"`
}

type Product struct {
	ID          uint64            `json:"id"`
	CreatedAt   time.Time         `json:"createdAt"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	ImagesURLs  []string          `json:"imagesURLs"`
	Weight      string            `json:"weight"`
	Dimensions  string            `json:"dimensions"`
	Categories  []string          `json:"categories"`
	Locations   []ProductLocation `json:"locations"`
	Prices      []ProductPrice    `json:"prices"`
}

type ProductLocation struct {
	ID        uint64    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UserID    uint64    `json:"userID"`
	ProductID uint64    `json:"productID"`
	Text      string    `json:"text"`
	Country   string    `json:"country"`
	Province  string    `json:"province"`
	City      string    `json:"city"`
	Area      string    `json:"area"`
	Street    string    `json:"street"`
	Building  string    `json:"building"`
	Store     string    `json:"store"`
	Longitude float64   `json:"longitude"`
	Latitude  float64   `json:"latitude"`
}

type ProductPrice struct {
	ID               uint64    `json:"id"`
	CreatedAt        time.Time `json:"createdAt"`
	UserID           uint64    `json:"userID"`
	ProductID        uint64    `json:"productID"`
	Currency         string    `json:"currency"`
	Price            uint64    `json:"price"`
	IsPriceEstimated bool      `json:"isPriceEstimated"`
}

type RefreshTokenInput struct {
	RefreshToken string `json:"refreshToken"`
}

type RegisterUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type TakeOrder struct {
	ID uint64 `json:"id"`
}

type UpdateOrderState struct {
	ID    uint64 `json:"id"`
	State string `json:"state"`
}

type UpdateProductLocation struct {
	ID        uint64   `json:"id"`
	Text      *string  `json:"text"`
	Country   *string  `json:"country"`
	Province  *string  `json:"province"`
	City      *string  `json:"city"`
	Area      *string  `json:"area"`
	Street    *string  `json:"street"`
	Building  *string  `json:"building"`
	Store     *string  `json:"store"`
	Longitude *float64 `json:"longitude"`
	Latitude  *float64 `json:"latitude"`
}

type UpdateProductPrice struct {
	ID               uint64  `json:"id"`
	Price            *uint64 `json:"price"`
	IsPriceEstimated *bool   `json:"isPriceEstimated"`
}

type UpdateUser struct {
	ID                uint64  `json:"id"`
	Name              *string `json:"name"`
	PhoneNumber       *string `json:"phoneNumber"`
	ProfilePictureURL *string `json:"profilePictureURL"`
	CurrencyMain      *string `json:"currencyMain"`
	CurrencySub       *string `json:"currencySub"`
}

type UpdateUserPassword struct {
	ID          uint64 `json:"id"`
	Password    string `json:"password"`
	NewPassword string `json:"newPassword"`
}

type User struct {
	ID                uint64    `json:"id"`
	CreatedAt         time.Time `json:"createdAt"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	PhoneNumber       string    `json:"phoneNumber"`
	ProfilePictureURL string    `json:"profilePictureURL"`
	CurrencyMain      string    `json:"currencyMain"`
	CurrencySub       *string   `json:"currencySub"`
	Addresses         []Address `json:"addresses"`
}
